/* Verified 2026-10-05 against PubMed/publisher pages. Each entry: design, year, n, plain-English finding, author institution. */
window.STUDIES = [
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/24338431/",
  "design": "Systematic review",
  "year": 2013,
  "n": 636,
  "description": "Cochrane review of 9 randomized trials (636 patients): electromagnetic field therapy gave about 15 points more pain relief (0-100 scale) than placebo in osteoarthritis, with no serious adverse events.",
  "location": "West China Hospital, Sichuan University, Chengdu, China (Cochrane review)",
  "category": "asia",
  "journal": "Cochrane Database Syst Rev",
  "author": "Li S",
  "highlight": true,
  "headline": "Cochrane review: more pain relief than placebo in osteoarthritis"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/38610722/",
  "design": "Systematic review",
  "year": 2024,
  "n": 1197,
  "description": "Systematic review of 17 randomized trials (1,197 patients): PEMF was associated with a 60% drop in VAS pain and 42% WOMAC improvement in osteoarthritis, plus better quality of life.",
  "location": "Fondazione Policlinico Universitario A. Gemelli IRCCS / Catholic University of the Sacred Heart, Rome, Italy",
  "category": "europe",
  "journal": "J Clin Med",
  "author": "Cianni L",
  "highlight": true,
  "headline": "17 trials, 1,197 patients: osteoarthritis pain down 60%"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/39928254/",
  "design": "RCT",
  "year": 2025,
  "n": 120,
  "description": "Multi-center randomized trial in 120 patients with joint or soft-tissue pain: over 14 days PEMF cut pain 36% versus 10% with standard care and reduced pain-medication use by 55%.",
  "location": "Andrews Institute (Pensacola, FL), Northwell (NY), Rothman Orthopaedic Institute (NJ) and other US orthopedic clinics",
  "category": "usa",
  "journal": "Pain Ther",
  "author": "Hackel JG",
  "highlight": true,
  "headline": "2025 trial: pain down 36% vs 10% with standard care"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/40388433/",
  "design": "Meta-analysis",
  "year": 2025,
  "n": 252,
  "description": "Meta-analysis of 4 randomized trials (252 patients) with shoulder impingement: PEMF reduced short-term pain and improved short- and long-term shoulder function.",
  "location": "Kaohsiung Medical University, Kaohsiung, Taiwan",
  "category": "asia",
  "journal": "PLoS One",
  "author": "Wang HY"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/35077249/",
  "design": "Meta-analysis",
  "year": 2022,
  "n": 618,
  "description": "Meta-analysis of 14 RCTs (618 participants) finding PEMF relieved pain more than placebo in low back pain, particularly chronic low back pain; physical function did not differ.",
  "location": "West China Hospital, Sichuan University, Chengdu, China",
  "category": "asia",
  "journal": "Clinical Rehabilitation",
  "author": "Sun X"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/32495506/",
  "design": "Meta-analysis",
  "year": 2020,
  "n": 1468,
  "description": "Meta-analysis of 22 randomized trials (1,468 fracture patients): PEMF raised the healing rate to 79.7% versus 64.3% with sham and reduced fracture pain.",
  "location": "West China Hospital, Sichuan University, Chengdu, China",
  "category": "asia",
  "journal": "Bioelectromagnetics",
  "author": "Peng L"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/32251502/",
  "design": "Meta-analysis",
  "year": 2020,
  "n": null,
  "description": "Meta-analysis of placebo-controlled RCTs (16 studies reviewed) finding PEMF beneficial over placebo for osteoarthritis pain, stiffness and physical function, with clinically significant short-term pain effects.",
  "location": "West China Hospital, Sichuan University, Chengdu, China; University of Oxford, UK",
  "category": "asia",
  "journal": "Physical Therapy",
  "author": "Yang X"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/37999784/",
  "design": "Systematic review",
  "year": 2023,
  "n": 420,
  "description": "Medical University of Vienna review of 9 randomized trials (420 patients): PEMF appears safe and beneficial for non-specific low back pain, especially when added to physiotherapy.",
  "location": "Medical University of Vienna, Austria",
  "category": "europe",
  "journal": "Wien Med Wochenschr",
  "author": "Kull P"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/35362792/",
  "design": "Systematic review",
  "year": 2022,
  "n": null,
  "description": "Medical University of Vienna review of 10 systematic reviews: PEMF appears effective in the short term for relieving pain and improving function in osteoarthritis.",
  "location": "Medical University of Vienna, Austria",
  "category": "europe",
  "journal": "Wien Klin Wochenschr",
  "author": "Markovic L"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/32606905/",
  "design": "Systematic review",
  "year": 2020,
  "n": null,
  "description": "Systematic review of 21 randomized trials: low-intensity, low-frequency pulsed magnetic fields were effective and well tolerated for acute and chronic musculoskeletal pain.",
  "location": "G. D'Annunzio University of Chieti-Pescara, Italy",
  "category": "europe",
  "journal": "J Pain Res",
  "author": "Paolucci T"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/22504115/",
  "design": "Systematic review",
  "year": 2013,
  "n": 930,
  "description": "Systematic review of 14 placebo-controlled trials (930 patients) with knee osteoarthritis: in high-quality trials PEMF reduced pain at 4 and 8 weeks, and function improved at 8 weeks.",
  "location": "Medifarm Hospital, Suncheon, South Korea",
  "category": "asia",
  "journal": "Rheumatology (Oxford)",
  "author": "Ryang We S"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/39478814/",
  "design": "RCT",
  "year": 2024,
  "n": 60,
  "description": "Randomized trial in 60 people with end-stage knee osteoarthritis: adding PEMF to home exercise improved knee muscle strength and reduced pain more than exercise alone, notably in women and over-70s.",
  "location": "Chinese University of Hong Kong, Prince of Wales Hospital, Hong Kong, China",
  "category": "asia",
  "journal": "Frontiers in Medicine",
  "author": "Wang QW"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/39597053/",
  "design": "RCT",
  "year": 2024,
  "n": 47,
  "description": "Double-blind RCT in 47 adults with chronic rhinosinusitis: one month of PEMF reduced fatigue and headache more than an inactive device and improved sinus findings on CT.",
  "location": "Cairo University, Giza, Egypt",
  "category": "other",
  "journal": "Medicina (Kaunas)",
  "author": "Abed Elrashid NA"
 },
 {
  "link": "https://doi.org/10.18203/2320-6012.ijrms20232851",
  "design": "RCT",
  "year": 2023,
  "n": 27,
  "description": "Patient-blinded randomized trial in chronic low back pain: adding PEMF to standard physiotherapy improved pain, disability and lumbar range of motion more than sham.",
  "location": "Istanbul Aydin University, Istanbul, Turkey",
  "category": "other",
  "journal": "International Journal of Research in Medical Sciences",
  "author": "Yavas AD"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/36922781/",
  "design": "RCT",
  "year": 2023,
  "n": 40,
  "description": "Randomized trial in 40 people with early knee osteoarthritis: six PEMF sessions reduced pain and improved function significantly more than low-level laser therapy, with no adverse events.",
  "location": "University of Haifa, Haifa, Israel",
  "category": "other",
  "journal": "BMC Geriatrics",
  "author": "Elboim-Gabyzon M"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/36465321/",
  "design": "RCT",
  "year": 2022,
  "n": 21,
  "description": "Single-blind placebo-controlled pilot in 21 women with fibromyalgia: PEMF reduced widespread pain, symptom severity and pain scores significantly more than placebo and was safe.",
  "location": "ASL3 Genovese, Genoa, and IRCCS Humanitas Research Hospital, Milan, Italy",
  "category": "europe",
  "journal": "Rheumatology and Immunology Research",
  "author": "Giovale M"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/32401418/",
  "design": "RCT",
  "year": 2020,
  "n": 30,
  "description": "Mayo Clinic controlled study in 30 adults with hypertension: 12 weeks of PEMF lowered systolic and diastolic blood pressure and improved blood-vessel function, while controls did not change.",
  "location": "Mayo Clinic, Rochester (MN) & Phoenix (AZ), USA",
  "category": "usa",
  "journal": "J Clin Hypertens (Greenwich)",
  "author": "Stewart GM"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/31394939/",
  "design": "RCT",
  "year": 2020,
  "n": 44,
  "description": "Mayo Clinic double-blind randomized trial in 44 adults with metabolic syndrome: 12 weeks of PEMF raised plasma nitric oxide and lowered exercise blood pressure, most clearly in those with hypertension.",
  "location": "Mayo Clinic, Rochester (MN) & Phoenix (AZ), USA",
  "category": "usa",
  "journal": "Blood Press",
  "author": "Kim CH"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/31385489/",
  "design": "RCT",
  "year": 2019,
  "n": null,
  "description": "Randomized sham-controlled study in cervical disc herniation: adding PEMF to standard physiotherapy gave greater pain relief and better sleep at 12 weeks and was safe for routine use.",
  "location": "Dicle University, Diyarbakir, Turkey",
  "category": "other",
  "journal": "Turkish Journal of Medical Sciences",
  "author": "Hattapoglu E"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/29950893/",
  "design": "RCT",
  "year": 2018,
  "n": 36,
  "description": "Pilot double-blind, sham-controlled trial in 36 patients with persistent pain after lumbar surgery; one PEMF setting cut low-back pain 40% vs 26% with sham, showing a favourable trend.",
  "location": "Alabama Orthopedic Center, Birmingham, Alabama, USA (with Regenesis Biomedical, Scottsdale, Arizona)",
  "category": "usa",
  "journal": "Journal of Pain Research",
  "author": "Sorrell RG"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/26705327/",
  "design": "RCT",
  "year": 2016,
  "n": 60,
  "description": "Double-blind placebo-controlled trial in 60 knee osteoarthritis patients: one month of wearable PEMF reduced pain and improved function, and 26% stopped NSAIDs/painkillers.",
  "location": "University of Messina, Italy",
  "category": "europe",
  "journal": "Rheumatology (Oxford)",
  "author": "Bagnato GL"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/23331333/",
  "design": "RCT",
  "year": 2013,
  "n": 58,
  "description": "Randomized sham-controlled study of 58 patients with delayed fracture healing: early PEMF achieved a 77.4% union rate versus 48.1% with sham treatment.",
  "location": "Nanjing Drum Tower Hospital, Nanjing University Medical School, Nanjing, China",
  "category": "asia",
  "journal": "BMC Musculoskeletal Disorders",
  "author": "Shi HF"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/19920724/",
  "design": "RCT",
  "year": 2009,
  "n": 56,
  "description": "Double-blind, sham-controlled trial in 56 women with fibromyalgia: three weeks of PEMF improved pain, function, fatigue and global status, with pain gains maintained at 12 weeks.",
  "location": "Ankara Physical Medicine and Rehabilitation Education and Research Hospital, Ankara, Turkey",
  "category": "other",
  "journal": "Clinical Journal of Pain",
  "author": "Sutbeyaz ST"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/18080043/",
  "design": "RCT",
  "year": 2007,
  "n": 32,
  "description": "Double-blind, sham-controlled pilot trial of a head-worn PEMF device in chronic pain; fibromyalgia patients showed a trend toward greater pain relief than sham, warranting a larger trial.",
  "location": "Lawson Health Research Institute, University of Western Ontario, London, Ontario, Canada",
  "category": "canada-australia",
  "journal": "Pain Research & Management",
  "author": "Thomas AW"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/15986086/",
  "design": "RCT",
  "year": 2006,
  "n": 34,
  "description": "Double-blind, sham-controlled trial in 34 patients with neck osteoarthritis: three weeks of whole-body PEMF reduced pain and improved neck movement and disability scores; sham did not.",
  "location": "Ankara Physical Medicine and Rehabilitation Education and Research Hospital, Ankara, Turkey",
  "category": "other",
  "journal": "Rheumatology International",
  "author": "Sutbeyaz ST"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/11279973/",
  "design": "RCT",
  "year": 1999,
  "n": 42,
  "description": "Double-blind, placebo-controlled study in 42 migraine sufferers: 73% of those receiving PEMF reported fewer headaches in the following month, versus half of the placebo group.",
  "location": "Madigan Army Medical Center, Tacoma, Washington, USA",
  "category": "usa",
  "journal": "Headache",
  "author": "Sherman RA"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/7837158/",
  "design": "RCT",
  "year": 1994,
  "n": 167,
  "description": "Randomized double-blind placebo-controlled trials in 167 patients with knee or neck osteoarthritis: PEMF significantly reduced pain and pain on motion compared with placebo.",
  "location": "Danbury Hospital, Danbury, Connecticut, USA",
  "category": "usa",
  "journal": "J Rheumatol",
  "author": "Trock DH"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/8478852/",
  "design": "RCT",
  "year": 1993,
  "n": 27,
  "description": "Pilot double-blind randomized trial in 27 osteoarthritis patients: PEMF improved clinical measures by 23-61% versus 2-18% with placebo, with no toxicity observed.",
  "location": "Danbury Hospital, Danbury, Connecticut, USA",
  "category": "usa",
  "journal": "J Rheumatol",
  "author": "Trock DH"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/36934330/",
  "design": "Clinical study",
  "year": 2023,
  "n": 101,
  "description": "Community case study of 101 adults: brief weekly PEMF sessions over 12 weeks were associated with better mobility, more muscle mass, less fat and reduced pain, especially in older participants.",
  "location": "National University of Singapore and QuantumTx, Singapore",
  "category": "asia",
  "journal": "Aging (Albany NY)",
  "author": "Venugobal S"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/7054564/",
  "design": "Clinical study",
  "year": 1982,
  "n": 1078,
  "description": "Report on 1,007 ununited fractures and 71 failed fusions treated non-surgically with PEMF: success rates were 81% at Columbia-Presbyterian and 79% internationally.",
  "location": "Columbia-Presbyterian Medical Center (Columbia University), New York, USA",
  "category": "usa",
  "journal": "JAMA",
  "author": "Bassett CA"
 },
 {
  "link": "https://doi.org/10.33235/wpr.32.2.58-65",
  "design": "Review",
  "year": 2024,
  "n": null,
  "description": "Literature review of PEMF in wound healing, reporting studies where PEMF improved microcirculation and shortened healing time in diabetic foot ulcers, and calling for more controlled trials.",
  "location": "Medical University of South Carolina, Charleston, South Carolina, USA",
  "category": "usa",
  "journal": "Wound Practice and Research",
  "author": "Helmy J"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/26042793/",
  "design": "Review",
  "year": 2015,
  "n": null,
  "description": "Wake Forest review of laboratory studies showing that specific low-frequency electromagnetic field settings can enhance bone- and cartilage-forming differentiation of human bone-marrow stem cells.",
  "location": "Wake Forest Institute for Regenerative Medicine, Winston-Salem, North Carolina, USA",
  "category": "usa",
  "journal": "Stem Cell Res",
  "author": "Ross CL"
 },
 {
  "link": "https://doi.org/10.13005/bpj/448",
  "design": "Review",
  "year": 2014,
  "n": null,
  "description": "Review of electromagnetic therapies, including PEMF, for fractures, arthritis and osteoporosis, comparing techniques and summarising proposed mechanisms of action.",
  "location": "Ahvaz Jundishapur University of Medical Sciences, Ahvaz, Iran",
  "category": "other",
  "journal": "Biomedical and Pharmacology Journal",
  "author": "Yadollahpour A"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/19371845/",
  "design": "Review",
  "year": 2009,
  "n": null,
  "description": "Review of PEMF in plastic surgery describing its use to manage post-surgical pain and swelling and chronic wounds, with no known side effects.",
  "location": "Albert Einstein College of Medicine / Montefiore, Bronx, New York, USA",
  "category": "usa",
  "journal": "Aesthet Surg J",
  "author": "Strauch B"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/17886012/",
  "design": "Review",
  "year": 2007,
  "n": null,
  "description": "Review by M.S. Markov describing the growing medical use of pulsed electromagnetic field therapy as a non-invasive option for musculoskeletal problems and pain relief.",
  "location": "Research International, Williamsville, New York, USA",
  "category": "usa",
  "journal": "Electromagn Biol Med",
  "author": "Markov MS"
 },
 {
  "link": "https://pubmed.ncbi.nlm.nih.gov/26780754/",
  "design": "Lab study",
  "year": 2016,
  "n": null,
  "description": "Laboratory study on human spinal-disc cells: PEMF reduced inflammation-driven expression of several genes linked to disc degeneration, supporting further clinical research.",
  "location": "University of California, San Francisco (with Orthofix Inc.), USA",
  "category": "usa",
  "journal": "Spine J",
  "author": "Miller SL"
 }
];
